name: "Build test and deploy app on main"

on:
  push:
    branches: ["main", "testing-ci"]
  pull_request:
    branches: ["main", "testing-ci"]

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  build-image:
    needs: unit-tests
    uses: ./.github/workflows/docker-image-build.yaml
    secrets:
      dockerhub_token: ${{ secrets.DELTA_TASK_DOCKERHUB_PUSH_TOKEN }}
