name: "Build test and deploy app"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml
#
#   build-image:
#     uses: ./.github/workflows/docker-image-build.yaml
