name: "Build test and deploy app on main"

on:
  push:
    branches: ["main", "testing-ci"]
  pull_request:
    branches: ["main", "testing-ci"]

jobs:
  #TODO: Static code analysis

  #TODO Build once and run unit-tests upon the container (viz README)
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  build-image:
    needs: unit-tests
    uses: ./.github/workflows/docker-image-build.yaml
    secrets:
      dockerhub_token: ${{ secrets.DELTA_TASK_DOCKERHUB_PUSH_TOKEN }}

  system-tests:
    needs: build-image
    uses: ./.github/workflows/system-tests.yaml

  push-as-latest:
    needs: system-tests
    uses: ./.github/workflows/docker-image-build.yaml
    secrets:
      dockerhub_token: ${{ secrets.DELTA_TASK_DOCKERHUB_PUSH_TOKEN }}
    with:
      ref_name: "latest"

  promote-to-deploy:
    needs: push-as-latest
    uses: ./.github/workflows/promote-to-deploy.yaml
