name: "Build test and deploy app on testing-ci branch"

on:
  push:
    branches: ["testing-ci"]
  pull_request:
    branches: ["testing-ci"]

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  build-image:
    needs: unit-tests
    uses: ./.github/workflows/docker-image-build.yaml
