name: Docker Image CI

on:
  workflow_call:

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        #TODO: make sure it does not break on PRs
        # Search github.ref_name
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
        # run: docker build . --file Dockerfile --tag "kairixir/hello-world-go:${{ github.ref_name }}"
        run: echo "skipped"

      - name: Push Docker image to DokcerHub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DELTA_TASK_DOCKERHUB_PUSH_TOKEN }}

        run: |
          echo "DOCKERHUB_TOKEN"
          # docker login -u kairixir -p "$DOCKERHUB_TOKEN" 
          # docker push "kairixir/hello-world-go:${{ github.ref_name }}"
