name: System tests

on:
  workflow_call:

jobs:
  test-server-alive:
    runs-on: ubuntu-latest
    steps:
      - name: "Pull container"
        run: |
          docker pull "kairixir/hello-world-go:${{ github.ref_name }}"
      - name: "Run test"
        run: |
          docker run -d -p 8080:8080 "kairixir/hello-world-go:${{ github.ref_name }}"
          curl -vL localhost:8080

  test-server-returns-expected-string:
    runs-on: ubuntu-latest
    steps:
      - name: "Pull container"
        run: |
          docker pull "kairixir/hello-world-go:${{ github.ref_name }}"
      - name: "Run test"
        run: |
          docker run -d -p 8080:8080 "kairixir/hello-world-go:${{ github.ref_name }}"
          curl -sL localhost:8080 && grep 'Hello World!'
